package domain

import "errors"

var (
	ErrAppNotFound                   = errors.New("app not found")
	ErrAppNameTaken                  = errors.New("app name already in use")
	ErrAppNameInvalid                = errors.New("app name is invalid")
	ErrDeploymentNotFound            = errors.New("deployment not found")
	ErrDeploymentActive              = errors.New("deployment is already active")
	ErrDeploymentNotRollbackable     = errors.New("deployment is not eligible for rollback")
	ErrDeploymentNotCancellable      = errors.New("deployment is not cancellable")
	ErrDeploymentNotRetryable        = errors.New("deployment is not eligible for retry")
	ErrDeploymentRetryUnavailable    = errors.New("retry is only available for Git deployments")
	ErrDeploymentCancelled           = errors.New("deployment cancelled")
	ErrBuildFailed                   = errors.New("build failed")
	ErrInvalidCredentials            = errors.New("invalid credentials")
	ErrUnauthorized                  = errors.New("unauthorized")
	ErrEnvKeyInvalid                 = errors.New("env key is invalid")
	ErrEnvVarNotFound                = errors.New("env var not found")
	ErrGitSourceNotFound             = errors.New("git source not configured")
	ErrGitRepositoryInvalid          = errors.New("GitHub repository is invalid")
	ErrGitRefInvalid                 = errors.New("git ref is invalid")
	ErrGitPathInvalid                = errors.New("git build path is invalid")
	ErrDockerfileNotFound            = errors.New("Dockerfile not found in the configured build context")
	ErrGitHubAppNotConfigured        = errors.New("GitHub App integration is not configured")
	ErrGitHubInstallationNotFound    = errors.New("GitHub App installation not found")
	ErrGitHubInstallationInvalid     = errors.New("GitHub App installation is invalid")
	ErrGitHubRepositoryNotAccessible = errors.New("repository is not accessible to the GitHub App installation")
	ErrGitHubWebhookNotConfigured    = errors.New("GitHub webhook integration is not configured")
	ErrGitHubWebhookSignatureInvalid = errors.New("GitHub webhook signature is invalid")
	ErrGitHubAutoDeployRequiresApp   = errors.New("auto-deploy requires a GitHub App repository")
	ErrCustomDomainNotFound          = errors.New("custom domain not found")
	ErrCustomDomainTaken             = errors.New("custom domain already in use")
	ErrCustomDomainInvalid           = errors.New("custom domain is invalid")
	ErrCustomDomainDNSNotConfigured  = errors.New("custom domain DNS is not configured for this MiniPaaS instance")
	ErrCustomDomainNotVerified       = errors.New("custom domain has not been verified")
)
