// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: app.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApp = `-- name: CreateApp :one
INSERT INTO apps (name)
VALUES ($1)
RETURNING id, name, status, created_at, updated_at
`

func (q *Queries) CreateApp(ctx context.Context, name string) (App, error) {
	row := q.db.QueryRow(ctx, createApp, name)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteApp = `-- name: DeleteApp :exec
DELETE FROM apps WHERE id = $1
`

func (q *Queries) DeleteApp(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteApp, id)
	return err
}

const getAppByID = `-- name: GetAppByID :one
SELECT id, name, status, created_at, updated_at FROM apps
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetAppByID(ctx context.Context, id pgtype.UUID) (App, error) {
	row := q.db.QueryRow(ctx, getAppByID, id)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAppByName = `-- name: GetAppByName :one
SELECT id, name, status, created_at, updated_at FROM apps
WHERE name = $1
LIMIT 1
`

func (q *Queries) GetAppByName(ctx context.Context, name string) (App, error) {
	row := q.db.QueryRow(ctx, getAppByName, name)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApps = `-- name: ListApps :many
SELECT id, name, status, created_at, updated_at FROM apps
ORDER BY created_at DESC
`

func (q *Queries) ListApps(ctx context.Context) ([]App, error) {
	rows, err := q.db.Query(ctx, listApps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []App
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAppStatus = `-- name: UpdateAppStatus :exec
UPDATE apps
SET status = $1, updated_at = now()
WHERE id = $2
`

type UpdateAppStatusParams struct {
	Status string      `json:"status"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateAppStatus(ctx context.Context, arg UpdateAppStatusParams) error {
	_, err := q.db.Exec(ctx, updateAppStatus, arg.Status, arg.ID)
	return err
}
