// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditEvent = `-- name: CreateAuditEvent :exec
INSERT INTO audit_events (user_id, action, method, path, status_code, request_id)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateAuditEventParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	Action     string      `json:"action"`
	Method     string      `json:"method"`
	Path       string      `json:"path"`
	StatusCode int32       `json:"status_code"`
	RequestID  string      `json:"request_id"`
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) error {
	_, err := q.db.Exec(ctx, createAuditEvent,
		arg.UserID,
		arg.Action,
		arg.Method,
		arg.Path,
		arg.StatusCode,
		arg.RequestID,
	)
	return err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, user_id, action, method, path, status_code, request_id, created_at
FROM audit_events
ORDER BY id DESC
LIMIT $2 OFFSET $1
`

type ListAuditEventsParams struct {
	Offset int32 `json:"offset"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEvents, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.Method,
			&i.Path,
			&i.StatusCode,
			&i.RequestID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
