// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: custom_domain.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomDomain = `-- name: CreateCustomDomain :one
INSERT INTO custom_domains (app_id, hostname)
VALUES ($1, $2)
RETURNING id, app_id, hostname, status, last_error, verified_at, created_at, updated_at
`

type CreateCustomDomainParams struct {
	AppID    pgtype.UUID `json:"app_id"`
	Hostname string      `json:"hostname"`
}

func (q *Queries) CreateCustomDomain(ctx context.Context, arg CreateCustomDomainParams) (CustomDomain, error) {
	row := q.db.QueryRow(ctx, createCustomDomain, arg.AppID, arg.Hostname)
	var i CustomDomain
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Hostname,
		&i.Status,
		&i.LastError,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCustomDomain = `-- name: DeleteCustomDomain :exec
DELETE FROM custom_domains WHERE id = $1
`

func (q *Queries) DeleteCustomDomain(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCustomDomain, id)
	return err
}

const getCustomDomain = `-- name: GetCustomDomain :one
SELECT id, app_id, hostname, status, last_error, verified_at, created_at, updated_at FROM custom_domains WHERE id = $1
`

func (q *Queries) GetCustomDomain(ctx context.Context, id pgtype.UUID) (CustomDomain, error) {
	row := q.db.QueryRow(ctx, getCustomDomain, id)
	var i CustomDomain
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Hostname,
		&i.Status,
		&i.LastError,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCustomDomainsByApp = `-- name: ListCustomDomainsByApp :many
SELECT id, app_id, hostname, status, last_error, verified_at, created_at, updated_at FROM custom_domains
WHERE app_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListCustomDomainsByApp(ctx context.Context, appID pgtype.UUID) ([]CustomDomain, error) {
	rows, err := q.db.Query(ctx, listCustomDomainsByApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomDomain
	for rows.Next() {
		var i CustomDomain
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.Hostname,
			&i.Status,
			&i.LastError,
			&i.VerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomDomainVerification = `-- name: UpdateCustomDomainVerification :exec
UPDATE custom_domains
SET status = $1,
    last_error = $2,
    verified_at = $3,
    updated_at = now()
WHERE id = $4
`

type UpdateCustomDomainVerificationParams struct {
	Status     string             `json:"status"`
	LastError  pgtype.Text        `json:"last_error"`
	VerifiedAt pgtype.Timestamptz `json:"verified_at"`
	ID         pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdateCustomDomainVerification(ctx context.Context, arg UpdateCustomDomainVerificationParams) error {
	_, err := q.db.Exec(ctx, updateCustomDomainVerification,
		arg.Status,
		arg.LastError,
		arg.VerifiedAt,
		arg.ID,
	)
	return err
}
