// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployment.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (app_id, image_tag)
VALUES ($1, $2)
RETURNING id, app_id, image_tag, status, container_id, port, commit_sha, duration_ms, created_at, finished_at
`

type CreateDeploymentParams struct {
	AppID    pgtype.UUID `json:"app_id"`
	ImageTag string      `json:"image_tag"`
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, createDeployment, arg.AppID, arg.ImageTag)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.ImageTag,
		&i.Status,
		&i.ContainerID,
		&i.Port,
		&i.CommitSha,
		&i.DurationMs,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getActiveDeployment = `-- name: GetActiveDeployment :one
SELECT id, app_id, image_tag, status, container_id, port, commit_sha, duration_ms, created_at, finished_at FROM deployments
WHERE app_id = $1 AND status = 'running'
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveDeployment(ctx context.Context, appID pgtype.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, getActiveDeployment, appID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.ImageTag,
		&i.Status,
		&i.ContainerID,
		&i.Port,
		&i.CommitSha,
		&i.DurationMs,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getDeploymentByID = `-- name: GetDeploymentByID :one
SELECT id, app_id, image_tag, status, container_id, port, commit_sha, duration_ms, created_at, finished_at FROM deployments WHERE id = $1
`

func (q *Queries) GetDeploymentByID(ctx context.Context, id pgtype.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, getDeploymentByID, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.ImageTag,
		&i.Status,
		&i.ContainerID,
		&i.Port,
		&i.CommitSha,
		&i.DurationMs,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listDeploymentsByApp = `-- name: ListDeploymentsByApp :many
SELECT id, app_id, image_tag, status, container_id, port, commit_sha, duration_ms, created_at, finished_at FROM deployments
WHERE app_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListDeploymentsByAppParams struct {
	AppID pgtype.UUID `json:"app_id"`
	Lim   int32       `json:"lim"`
}

func (q *Queries) ListDeploymentsByApp(ctx context.Context, arg ListDeploymentsByAppParams) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listDeploymentsByApp, arg.AppID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.ImageTag,
			&i.Status,
			&i.ContainerID,
			&i.Port,
			&i.CommitSha,
			&i.DurationMs,
			&i.CreatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunningDeployments = `-- name: ListRunningDeployments :many
SELECT id, app_id, image_tag, status, container_id, port, commit_sha, duration_ms, created_at, finished_at FROM deployments WHERE status = 'running'
`

func (q *Queries) ListRunningDeployments(ctx context.Context) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listRunningDeployments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.ImageTag,
			&i.Status,
			&i.ContainerID,
			&i.Port,
			&i.CommitSha,
			&i.DurationMs,
			&i.CreatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeploymentRunning = `-- name: UpdateDeploymentRunning :exec
UPDATE deployments
SET status       = 'running',
    container_id = $1,
    port         = $2,
    image_tag    = $3,
    duration_ms  = $4,
    finished_at  = now()
WHERE id = $5
`

type UpdateDeploymentRunningParams struct {
	ContainerID pgtype.Text `json:"container_id"`
	Port        pgtype.Int4 `json:"port"`
	ImageTag    string      `json:"image_tag"`
	DurationMs  pgtype.Int4 `json:"duration_ms"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateDeploymentRunning(ctx context.Context, arg UpdateDeploymentRunningParams) error {
	_, err := q.db.Exec(ctx, updateDeploymentRunning,
		arg.ContainerID,
		arg.Port,
		arg.ImageTag,
		arg.DurationMs,
		arg.ID,
	)
	return err
}

const updateDeploymentStatus = `-- name: UpdateDeploymentStatus :exec
UPDATE deployments
SET status = $1, finished_at = now()
WHERE id = $2
`

type UpdateDeploymentStatusParams struct {
	Status string      `json:"status"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) error {
	_, err := q.db.Exec(ctx, updateDeploymentStatus, arg.Status, arg.ID)
	return err
}
