// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployment.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDeployments = `-- name: CountDeployments :one
SELECT COUNT(*)
FROM deployments d
JOIN apps a ON a.id = d.app_id
WHERE ($1::text IS NULL OR a.name = $1)
  AND ($2::text IS NULL OR d.status = $2)
`

type CountDeploymentsParams struct {
	AppName pgtype.Text `json:"app_name"`
	Status  pgtype.Text `json:"status"`
}

func (q *Queries) CountDeployments(ctx context.Context, arg CountDeploymentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDeployments, arg.AppName, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (app_id, image_tag)
VALUES ($1, $2)
RETURNING id, app_id, image_tag, status, container_id, port, commit_sha, duration_ms, created_at, finished_at, source_type, repository, branch, commit_author, commit_message, trigger_type, github_delivery_id, attempt, retry_of, cancel_requested
`

type CreateDeploymentParams struct {
	AppID    pgtype.UUID `json:"app_id"`
	ImageTag string      `json:"image_tag"`
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, createDeployment, arg.AppID, arg.ImageTag)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.ImageTag,
		&i.Status,
		&i.ContainerID,
		&i.Port,
		&i.CommitSha,
		&i.DurationMs,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.SourceType,
		&i.Repository,
		&i.Branch,
		&i.CommitAuthor,
		&i.CommitMessage,
		&i.TriggerType,
		&i.GithubDeliveryID,
		&i.Attempt,
		&i.RetryOf,
		&i.CancelRequested,
	)
	return i, err
}

const createDeploymentLog = `-- name: CreateDeploymentLog :one
INSERT INTO deployment_logs (deployment_id, stage, stream, message)
VALUES ($1, $2, $3, $4)
RETURNING id, deployment_id, stage, stream, message, created_at
`

type CreateDeploymentLogParams struct {
	DeploymentID pgtype.UUID `json:"deployment_id"`
	Stage        string      `json:"stage"`
	Stream       string      `json:"stream"`
	Message      string      `json:"message"`
}

func (q *Queries) CreateDeploymentLog(ctx context.Context, arg CreateDeploymentLogParams) (DeploymentLog, error) {
	row := q.db.QueryRow(ctx, createDeploymentLog,
		arg.DeploymentID,
		arg.Stage,
		arg.Stream,
		arg.Message,
	)
	var i DeploymentLog
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.Stage,
		&i.Stream,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const createGitDeployment = `-- name: CreateGitDeployment :one
INSERT INTO deployments (app_id, image_tag, source_type, repository, branch)
VALUES ($1, $2, 'git', $3, $4)
RETURNING id, app_id, image_tag, status, container_id, port, commit_sha, duration_ms, created_at, finished_at, source_type, repository, branch, commit_author, commit_message, trigger_type, github_delivery_id, attempt, retry_of, cancel_requested
`

type CreateGitDeploymentParams struct {
	AppID      pgtype.UUID `json:"app_id"`
	ImageTag   string      `json:"image_tag"`
	Repository pgtype.Text `json:"repository"`
	Branch     pgtype.Text `json:"branch"`
}

func (q *Queries) CreateGitDeployment(ctx context.Context, arg CreateGitDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, createGitDeployment,
		arg.AppID,
		arg.ImageTag,
		arg.Repository,
		arg.Branch,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.ImageTag,
		&i.Status,
		&i.ContainerID,
		&i.Port,
		&i.CommitSha,
		&i.DurationMs,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.SourceType,
		&i.Repository,
		&i.Branch,
		&i.CommitAuthor,
		&i.CommitMessage,
		&i.TriggerType,
		&i.GithubDeliveryID,
		&i.Attempt,
		&i.RetryOf,
		&i.CancelRequested,
	)
	return i, err
}

const createRetryGitDeployment = `-- name: CreateRetryGitDeployment :one
INSERT INTO deployments (app_id, image_tag, source_type, repository, branch, attempt, retry_of)
VALUES ($1, $2, 'git', $3, $4, $5, $6)
RETURNING id, app_id, image_tag, status, container_id, port, commit_sha, duration_ms, created_at, finished_at, source_type, repository, branch, commit_author, commit_message, trigger_type, github_delivery_id, attempt, retry_of, cancel_requested
`

type CreateRetryGitDeploymentParams struct {
	AppID      pgtype.UUID `json:"app_id"`
	ImageTag   string      `json:"image_tag"`
	Repository pgtype.Text `json:"repository"`
	Branch     pgtype.Text `json:"branch"`
	Attempt    int32       `json:"attempt"`
	RetryOf    pgtype.UUID `json:"retry_of"`
}

func (q *Queries) CreateRetryGitDeployment(ctx context.Context, arg CreateRetryGitDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, createRetryGitDeployment,
		arg.AppID,
		arg.ImageTag,
		arg.Repository,
		arg.Branch,
		arg.Attempt,
		arg.RetryOf,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.ImageTag,
		&i.Status,
		&i.ContainerID,
		&i.Port,
		&i.CommitSha,
		&i.DurationMs,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.SourceType,
		&i.Repository,
		&i.Branch,
		&i.CommitAuthor,
		&i.CommitMessage,
		&i.TriggerType,
		&i.GithubDeliveryID,
		&i.Attempt,
		&i.RetryOf,
		&i.CancelRequested,
	)
	return i, err
}

const createTriggeredGitDeployment = `-- name: CreateTriggeredGitDeployment :one
INSERT INTO deployments (app_id, image_tag, source_type, repository, branch, trigger_type, github_delivery_id)
VALUES ($1, $2, 'git', $3, $4, $5, $6)
RETURNING id, app_id, image_tag, status, container_id, port, commit_sha, duration_ms, created_at, finished_at, source_type, repository, branch, commit_author, commit_message, trigger_type, github_delivery_id, attempt, retry_of, cancel_requested
`

type CreateTriggeredGitDeploymentParams struct {
	AppID            pgtype.UUID `json:"app_id"`
	ImageTag         string      `json:"image_tag"`
	Repository       pgtype.Text `json:"repository"`
	Branch           pgtype.Text `json:"branch"`
	TriggerType      string      `json:"trigger_type"`
	GithubDeliveryID pgtype.Text `json:"github_delivery_id"`
}

func (q *Queries) CreateTriggeredGitDeployment(ctx context.Context, arg CreateTriggeredGitDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, createTriggeredGitDeployment,
		arg.AppID,
		arg.ImageTag,
		arg.Repository,
		arg.Branch,
		arg.TriggerType,
		arg.GithubDeliveryID,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.ImageTag,
		&i.Status,
		&i.ContainerID,
		&i.Port,
		&i.CommitSha,
		&i.DurationMs,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.SourceType,
		&i.Repository,
		&i.Branch,
		&i.CommitAuthor,
		&i.CommitMessage,
		&i.TriggerType,
		&i.GithubDeliveryID,
		&i.Attempt,
		&i.RetryOf,
		&i.CancelRequested,
	)
	return i, err
}

const getActiveDeployment = `-- name: GetActiveDeployment :one
SELECT id, app_id, image_tag, status, container_id, port, commit_sha, duration_ms, created_at, finished_at, source_type, repository, branch, commit_author, commit_message, trigger_type, github_delivery_id, attempt, retry_of, cancel_requested FROM deployments
WHERE app_id = $1 AND status = 'running'
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveDeployment(ctx context.Context, appID pgtype.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, getActiveDeployment, appID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.ImageTag,
		&i.Status,
		&i.ContainerID,
		&i.Port,
		&i.CommitSha,
		&i.DurationMs,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.SourceType,
		&i.Repository,
		&i.Branch,
		&i.CommitAuthor,
		&i.CommitMessage,
		&i.TriggerType,
		&i.GithubDeliveryID,
		&i.Attempt,
		&i.RetryOf,
		&i.CancelRequested,
	)
	return i, err
}

const getDeploymentByID = `-- name: GetDeploymentByID :one
SELECT id, app_id, image_tag, status, container_id, port, commit_sha, duration_ms, created_at, finished_at, source_type, repository, branch, commit_author, commit_message, trigger_type, github_delivery_id, attempt, retry_of, cancel_requested FROM deployments WHERE id = $1
`

func (q *Queries) GetDeploymentByID(ctx context.Context, id pgtype.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, getDeploymentByID, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.ImageTag,
		&i.Status,
		&i.ContainerID,
		&i.Port,
		&i.CommitSha,
		&i.DurationMs,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.SourceType,
		&i.Repository,
		&i.Branch,
		&i.CommitAuthor,
		&i.CommitMessage,
		&i.TriggerType,
		&i.GithubDeliveryID,
		&i.Attempt,
		&i.RetryOf,
		&i.CancelRequested,
	)
	return i, err
}

const listDeploymentLogs = `-- name: ListDeploymentLogs :many
SELECT id, deployment_id, stage, stream, message, created_at FROM deployment_logs
WHERE deployment_id = $1
  AND id > $2
ORDER BY id ASC
LIMIT $3
`

type ListDeploymentLogsParams struct {
	DeploymentID pgtype.UUID `json:"deployment_id"`
	AfterID      int64       `json:"after_id"`
	Lim          int32       `json:"lim"`
}

func (q *Queries) ListDeploymentLogs(ctx context.Context, arg ListDeploymentLogsParams) ([]DeploymentLog, error) {
	rows, err := q.db.Query(ctx, listDeploymentLogs, arg.DeploymentID, arg.AfterID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeploymentLog
	for rows.Next() {
		var i DeploymentLog
		if err := rows.Scan(
			&i.ID,
			&i.DeploymentID,
			&i.Stage,
			&i.Stream,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeployments = `-- name: ListDeployments :many
SELECT d.id, d.app_id, d.image_tag, d.status, d.container_id, d.port, d.commit_sha, d.duration_ms, d.created_at, d.finished_at, d.source_type, d.repository, d.branch, d.commit_author, d.commit_message, d.trigger_type, d.github_delivery_id, d.attempt, d.retry_of, d.cancel_requested, a.name AS app_name
FROM deployments d
JOIN apps a ON a.id = d.app_id
WHERE ($1::text IS NULL OR a.name = $1)
  AND ($2::text IS NULL OR d.status = $2)
ORDER BY d.created_at DESC
LIMIT $4 OFFSET $3
`

type ListDeploymentsParams struct {
	AppName pgtype.Text `json:"app_name"`
	Status  pgtype.Text `json:"status"`
	Off     int32       `json:"off"`
	Lim     int32       `json:"lim"`
}

type ListDeploymentsRow struct {
	ID               pgtype.UUID        `json:"id"`
	AppID            pgtype.UUID        `json:"app_id"`
	ImageTag         string             `json:"image_tag"`
	Status           string             `json:"status"`
	ContainerID      pgtype.Text        `json:"container_id"`
	Port             pgtype.Int4        `json:"port"`
	CommitSha        pgtype.Text        `json:"commit_sha"`
	DurationMs       pgtype.Int4        `json:"duration_ms"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	FinishedAt       pgtype.Timestamptz `json:"finished_at"`
	SourceType       string             `json:"source_type"`
	Repository       pgtype.Text        `json:"repository"`
	Branch           pgtype.Text        `json:"branch"`
	CommitAuthor     pgtype.Text        `json:"commit_author"`
	CommitMessage    pgtype.Text        `json:"commit_message"`
	TriggerType      string             `json:"trigger_type"`
	GithubDeliveryID pgtype.Text        `json:"github_delivery_id"`
	Attempt          int32              `json:"attempt"`
	RetryOf          pgtype.UUID        `json:"retry_of"`
	CancelRequested  bool               `json:"cancel_requested"`
	AppName          string             `json:"app_name"`
}

func (q *Queries) ListDeployments(ctx context.Context, arg ListDeploymentsParams) ([]ListDeploymentsRow, error) {
	rows, err := q.db.Query(ctx, listDeployments,
		arg.AppName,
		arg.Status,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeploymentsRow
	for rows.Next() {
		var i ListDeploymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.ImageTag,
			&i.Status,
			&i.ContainerID,
			&i.Port,
			&i.CommitSha,
			&i.DurationMs,
			&i.CreatedAt,
			&i.FinishedAt,
			&i.SourceType,
			&i.Repository,
			&i.Branch,
			&i.CommitAuthor,
			&i.CommitMessage,
			&i.TriggerType,
			&i.GithubDeliveryID,
			&i.Attempt,
			&i.RetryOf,
			&i.CancelRequested,
			&i.AppName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentsByApp = `-- name: ListDeploymentsByApp :many
SELECT id, app_id, image_tag, status, container_id, port, commit_sha, duration_ms, created_at, finished_at, source_type, repository, branch, commit_author, commit_message, trigger_type, github_delivery_id, attempt, retry_of, cancel_requested FROM deployments
WHERE app_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListDeploymentsByAppParams struct {
	AppID pgtype.UUID `json:"app_id"`
	Lim   int32       `json:"lim"`
}

func (q *Queries) ListDeploymentsByApp(ctx context.Context, arg ListDeploymentsByAppParams) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listDeploymentsByApp, arg.AppID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.ImageTag,
			&i.Status,
			&i.ContainerID,
			&i.Port,
			&i.CommitSha,
			&i.DurationMs,
			&i.CreatedAt,
			&i.FinishedAt,
			&i.SourceType,
			&i.Repository,
			&i.Branch,
			&i.CommitAuthor,
			&i.CommitMessage,
			&i.TriggerType,
			&i.GithubDeliveryID,
			&i.Attempt,
			&i.RetryOf,
			&i.CancelRequested,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentsForRetention = `-- name: ListDeploymentsForRetention :many
SELECT id, app_id, image_tag, status, container_id, port, commit_sha, duration_ms, created_at, finished_at, source_type, repository, branch, commit_author, commit_message, trigger_type, github_delivery_id, attempt, retry_of, cancel_requested FROM deployments
WHERE deployments.id IN (
    SELECT d.id FROM deployments d
    WHERE d.app_id = $1
    ORDER BY d.created_at DESC
    OFFSET $2
)
AND status NOT IN ('running', 'pending', 'building')
ORDER BY created_at DESC
`

type ListDeploymentsForRetentionParams struct {
	AppID pgtype.UUID `json:"app_id"`
	Keep  int32       `json:"keep"`
}

func (q *Queries) ListDeploymentsForRetention(ctx context.Context, arg ListDeploymentsForRetentionParams) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listDeploymentsForRetention, arg.AppID, arg.Keep)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.ImageTag,
			&i.Status,
			&i.ContainerID,
			&i.Port,
			&i.CommitSha,
			&i.DurationMs,
			&i.CreatedAt,
			&i.FinishedAt,
			&i.SourceType,
			&i.Repository,
			&i.Branch,
			&i.CommitAuthor,
			&i.CommitMessage,
			&i.TriggerType,
			&i.GithubDeliveryID,
			&i.Attempt,
			&i.RetryOf,
			&i.CancelRequested,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunningDeployments = `-- name: ListRunningDeployments :many
SELECT id, app_id, image_tag, status, container_id, port, commit_sha, duration_ms, created_at, finished_at, source_type, repository, branch, commit_author, commit_message, trigger_type, github_delivery_id, attempt, retry_of, cancel_requested FROM deployments WHERE status = 'running'
`

func (q *Queries) ListRunningDeployments(ctx context.Context) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listRunningDeployments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.ImageTag,
			&i.Status,
			&i.ContainerID,
			&i.Port,
			&i.CommitSha,
			&i.DurationMs,
			&i.CreatedAt,
			&i.FinishedAt,
			&i.SourceType,
			&i.Repository,
			&i.Branch,
			&i.CommitAuthor,
			&i.CommitMessage,
			&i.TriggerType,
			&i.GithubDeliveryID,
			&i.Attempt,
			&i.RetryOf,
			&i.CancelRequested,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeploymentCancelled = `-- name: MarkDeploymentCancelled :exec
UPDATE deployments
SET status = 'cancelled', cancel_requested = true, finished_at = now()
WHERE id = $1 AND status IN ('pending', 'building', 'cancel_requested')
`

func (q *Queries) MarkDeploymentCancelled(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markDeploymentCancelled, id)
	return err
}

const requestDeploymentCancel = `-- name: RequestDeploymentCancel :one
UPDATE deployments
SET status = 'cancel_requested', cancel_requested = true
WHERE id = $1 AND status IN ('pending', 'building', 'cancel_requested')
RETURNING id, app_id, image_tag, status, container_id, port, commit_sha, duration_ms, created_at, finished_at, source_type, repository, branch, commit_author, commit_message, trigger_type, github_delivery_id, attempt, retry_of, cancel_requested
`

func (q *Queries) RequestDeploymentCancel(ctx context.Context, id pgtype.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, requestDeploymentCancel, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.ImageTag,
		&i.Status,
		&i.ContainerID,
		&i.Port,
		&i.CommitSha,
		&i.DurationMs,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.SourceType,
		&i.Repository,
		&i.Branch,
		&i.CommitAuthor,
		&i.CommitMessage,
		&i.TriggerType,
		&i.GithubDeliveryID,
		&i.Attempt,
		&i.RetryOf,
		&i.CancelRequested,
	)
	return i, err
}

const updateDeploymentGitMetadata = `-- name: UpdateDeploymentGitMetadata :exec
UPDATE deployments
SET commit_sha = $1,
    commit_author = $2,
    commit_message = $3,
    branch = $4
WHERE id = $5
`

type UpdateDeploymentGitMetadataParams struct {
	CommitSha     pgtype.Text `json:"commit_sha"`
	CommitAuthor  pgtype.Text `json:"commit_author"`
	CommitMessage pgtype.Text `json:"commit_message"`
	Branch        pgtype.Text `json:"branch"`
	ID            pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateDeploymentGitMetadata(ctx context.Context, arg UpdateDeploymentGitMetadataParams) error {
	_, err := q.db.Exec(ctx, updateDeploymentGitMetadata,
		arg.CommitSha,
		arg.CommitAuthor,
		arg.CommitMessage,
		arg.Branch,
		arg.ID,
	)
	return err
}

const updateDeploymentRunning = `-- name: UpdateDeploymentRunning :exec
UPDATE deployments
SET status       = 'running',
    container_id = $1,
    port         = $2,
    image_tag    = $3,
    duration_ms  = $4,
    finished_at  = now()
WHERE id = $5
`

type UpdateDeploymentRunningParams struct {
	ContainerID pgtype.Text `json:"container_id"`
	Port        pgtype.Int4 `json:"port"`
	ImageTag    string      `json:"image_tag"`
	DurationMs  pgtype.Int4 `json:"duration_ms"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateDeploymentRunning(ctx context.Context, arg UpdateDeploymentRunningParams) error {
	_, err := q.db.Exec(ctx, updateDeploymentRunning,
		arg.ContainerID,
		arg.Port,
		arg.ImageTag,
		arg.DurationMs,
		arg.ID,
	)
	return err
}

const updateDeploymentStatus = `-- name: UpdateDeploymentStatus :exec
UPDATE deployments
SET status = $1, finished_at = now()
WHERE id = $2
`

type UpdateDeploymentStatusParams struct {
	Status string      `json:"status"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) error {
	_, err := q.db.Exec(ctx, updateDeploymentStatus, arg.Status, arg.ID)
	return err
}
