// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: env.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteEnvVar = `-- name: DeleteEnvVar :exec
DELETE FROM env_vars WHERE app_id = $1 AND key = $2
`

type DeleteEnvVarParams struct {
	AppID pgtype.UUID `json:"app_id"`
	Key   string      `json:"key"`
}

func (q *Queries) DeleteEnvVar(ctx context.Context, arg DeleteEnvVarParams) error {
	_, err := q.db.Exec(ctx, deleteEnvVar, arg.AppID, arg.Key)
	return err
}

const getEnvVar = `-- name: GetEnvVar :one
SELECT id, app_id, key, value, nonce, created_at, updated_at FROM env_vars
WHERE app_id = $1 AND key = $2
`

type GetEnvVarParams struct {
	AppID pgtype.UUID `json:"app_id"`
	Key   string      `json:"key"`
}

func (q *Queries) GetEnvVar(ctx context.Context, arg GetEnvVarParams) (EnvVar, error) {
	row := q.db.QueryRow(ctx, getEnvVar, arg.AppID, arg.Key)
	var i EnvVar
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Key,
		&i.Value,
		&i.Nonce,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnvVarsByApp = `-- name: GetEnvVarsByApp :many
SELECT id, app_id, key, value, nonce, created_at, updated_at FROM env_vars WHERE app_id = $1
`

func (q *Queries) GetEnvVarsByApp(ctx context.Context, appID pgtype.UUID) ([]EnvVar, error) {
	rows, err := q.db.Query(ctx, getEnvVarsByApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EnvVar
	for rows.Next() {
		var i EnvVar
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.Key,
			&i.Value,
			&i.Nonce,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvVarsByApp = `-- name: ListEnvVarsByApp :many
SELECT id, app_id, key, updated_at FROM env_vars
WHERE app_id = $1
ORDER BY key
`

type ListEnvVarsByAppRow struct {
	ID        pgtype.UUID        `json:"id"`
	AppID     pgtype.UUID        `json:"app_id"`
	Key       string             `json:"key"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListEnvVarsByApp(ctx context.Context, appID pgtype.UUID) ([]ListEnvVarsByAppRow, error) {
	rows, err := q.db.Query(ctx, listEnvVarsByApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnvVarsByAppRow
	for rows.Next() {
		var i ListEnvVarsByAppRow
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.Key,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEnvVar = `-- name: UpsertEnvVar :exec
INSERT INTO env_vars (app_id, key, value, nonce)
VALUES ($1, $2, $3, $4)
ON CONFLICT (app_id, key) DO UPDATE
SET value      = EXCLUDED.value,
    nonce      = EXCLUDED.nonce,
    updated_at = now()
`

type UpsertEnvVarParams struct {
	AppID pgtype.UUID `json:"app_id"`
	Key   string      `json:"key"`
	Value []byte      `json:"value"`
	Nonce []byte      `json:"nonce"`
}

func (q *Queries) UpsertEnvVar(ctx context.Context, arg UpsertEnvVarParams) error {
	_, err := q.db.Exec(ctx, upsertEnvVar,
		arg.AppID,
		arg.Key,
		arg.Value,
		arg.Nonce,
	)
	return err
}
