// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: git_source.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteGitSource = `-- name: DeleteGitSource :exec
DELETE FROM app_git_sources WHERE app_id = $1
`

func (q *Queries) DeleteGitSource(ctx context.Context, appID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGitSource, appID)
	return err
}

const getGitSource = `-- name: GetGitSource :one
SELECT app_id, repository, branch, build_context, dockerfile_path, created_at, updated_at, access_mode, github_installation_id, github_repository_id, private, auto_deploy FROM app_git_sources WHERE app_id = $1
`

func (q *Queries) GetGitSource(ctx context.Context, appID pgtype.UUID) (AppGitSource, error) {
	row := q.db.QueryRow(ctx, getGitSource, appID)
	var i AppGitSource
	err := row.Scan(
		&i.AppID,
		&i.Repository,
		&i.Branch,
		&i.BuildContext,
		&i.DockerfilePath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccessMode,
		&i.GithubInstallationID,
		&i.GithubRepositoryID,
		&i.Private,
		&i.AutoDeploy,
	)
	return i, err
}

const listAutoDeployGitSourcesByRepository = `-- name: ListAutoDeployGitSourcesByRepository :many
SELECT app_git_sources.app_id, app_git_sources.repository, app_git_sources.branch, app_git_sources.build_context, app_git_sources.dockerfile_path, app_git_sources.created_at, app_git_sources.updated_at, app_git_sources.access_mode, app_git_sources.github_installation_id, app_git_sources.github_repository_id, app_git_sources.private, app_git_sources.auto_deploy
FROM app_git_sources
WHERE github_repository_id = $1
  AND access_mode = 'github_app'
  AND auto_deploy = true
ORDER BY app_id
`

func (q *Queries) ListAutoDeployGitSourcesByRepository(ctx context.Context, githubRepositoryID pgtype.Int8) ([]AppGitSource, error) {
	rows, err := q.db.Query(ctx, listAutoDeployGitSourcesByRepository, githubRepositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppGitSource
	for rows.Next() {
		var i AppGitSource
		if err := rows.Scan(
			&i.AppID,
			&i.Repository,
			&i.Branch,
			&i.BuildContext,
			&i.DockerfilePath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccessMode,
			&i.GithubInstallationID,
			&i.GithubRepositoryID,
			&i.Private,
			&i.AutoDeploy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setGitSourceAutoDeploy = `-- name: SetGitSourceAutoDeploy :one
UPDATE app_git_sources
SET auto_deploy = $1, updated_at = now()
WHERE app_id = $2
RETURNING app_id, repository, branch, build_context, dockerfile_path, created_at, updated_at, access_mode, github_installation_id, github_repository_id, private, auto_deploy
`

type SetGitSourceAutoDeployParams struct {
	AutoDeploy bool        `json:"auto_deploy"`
	AppID      pgtype.UUID `json:"app_id"`
}

func (q *Queries) SetGitSourceAutoDeploy(ctx context.Context, arg SetGitSourceAutoDeployParams) (AppGitSource, error) {
	row := q.db.QueryRow(ctx, setGitSourceAutoDeploy, arg.AutoDeploy, arg.AppID)
	var i AppGitSource
	err := row.Scan(
		&i.AppID,
		&i.Repository,
		&i.Branch,
		&i.BuildContext,
		&i.DockerfilePath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccessMode,
		&i.GithubInstallationID,
		&i.GithubRepositoryID,
		&i.Private,
		&i.AutoDeploy,
	)
	return i, err
}

const upsertGitSource = `-- name: UpsertGitSource :one
INSERT INTO app_git_sources (app_id, repository, branch, build_context, dockerfile_path, access_mode, github_installation_id, github_repository_id, private)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (app_id) DO UPDATE SET
    repository = EXCLUDED.repository,
    branch = EXCLUDED.branch,
    build_context = EXCLUDED.build_context,
    dockerfile_path = EXCLUDED.dockerfile_path,
    access_mode = EXCLUDED.access_mode,
    github_installation_id = EXCLUDED.github_installation_id,
    github_repository_id = EXCLUDED.github_repository_id,
    private = EXCLUDED.private,
    auto_deploy = CASE WHEN EXCLUDED.access_mode = 'public' THEN false ELSE app_git_sources.auto_deploy END,
    updated_at = now()
RETURNING app_id, repository, branch, build_context, dockerfile_path, created_at, updated_at, access_mode, github_installation_id, github_repository_id, private, auto_deploy
`

type UpsertGitSourceParams struct {
	AppID                pgtype.UUID `json:"app_id"`
	Repository           string      `json:"repository"`
	Branch               string      `json:"branch"`
	BuildContext         string      `json:"build_context"`
	DockerfilePath       string      `json:"dockerfile_path"`
	AccessMode           string      `json:"access_mode"`
	GithubInstallationID pgtype.Int8 `json:"github_installation_id"`
	GithubRepositoryID   pgtype.Int8 `json:"github_repository_id"`
	Private              bool        `json:"private"`
}

func (q *Queries) UpsertGitSource(ctx context.Context, arg UpsertGitSourceParams) (AppGitSource, error) {
	row := q.db.QueryRow(ctx, upsertGitSource,
		arg.AppID,
		arg.Repository,
		arg.Branch,
		arg.BuildContext,
		arg.DockerfilePath,
		arg.AccessMode,
		arg.GithubInstallationID,
		arg.GithubRepositoryID,
		arg.Private,
	)
	var i AppGitSource
	err := row.Scan(
		&i.AppID,
		&i.Repository,
		&i.Branch,
		&i.BuildContext,
		&i.DockerfilePath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccessMode,
		&i.GithubInstallationID,
		&i.GithubRepositoryID,
		&i.Private,
		&i.AutoDeploy,
	)
	return i, err
}
