// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: git_source.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteGitSource = `-- name: DeleteGitSource :exec
DELETE FROM app_git_sources WHERE app_id = $1
`

func (q *Queries) DeleteGitSource(ctx context.Context, appID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGitSource, appID)
	return err
}

const getGitSource = `-- name: GetGitSource :one
SELECT app_id, repository, branch, build_context, dockerfile_path, created_at, updated_at, access_mode, github_installation_id, github_repository_id, private FROM app_git_sources WHERE app_id = $1
`

func (q *Queries) GetGitSource(ctx context.Context, appID pgtype.UUID) (AppGitSource, error) {
	row := q.db.QueryRow(ctx, getGitSource, appID)
	var i AppGitSource
	err := row.Scan(
		&i.AppID,
		&i.Repository,
		&i.Branch,
		&i.BuildContext,
		&i.DockerfilePath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccessMode,
		&i.GithubInstallationID,
		&i.GithubRepositoryID,
		&i.Private,
	)
	return i, err
}

const upsertGitSource = `-- name: UpsertGitSource :one
INSERT INTO app_git_sources (app_id, repository, branch, build_context, dockerfile_path, access_mode, github_installation_id, github_repository_id, private)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (app_id) DO UPDATE SET
    repository = EXCLUDED.repository,
    branch = EXCLUDED.branch,
    build_context = EXCLUDED.build_context,
    dockerfile_path = EXCLUDED.dockerfile_path,
    access_mode = EXCLUDED.access_mode,
    github_installation_id = EXCLUDED.github_installation_id,
    github_repository_id = EXCLUDED.github_repository_id,
    private = EXCLUDED.private,
    updated_at = now()
RETURNING app_id, repository, branch, build_context, dockerfile_path, created_at, updated_at, access_mode, github_installation_id, github_repository_id, private
`

type UpsertGitSourceParams struct {
	AppID                pgtype.UUID `json:"app_id"`
	Repository           string      `json:"repository"`
	Branch               string      `json:"branch"`
	BuildContext         string      `json:"build_context"`
	DockerfilePath       string      `json:"dockerfile_path"`
	AccessMode           string      `json:"access_mode"`
	GithubInstallationID pgtype.Int8 `json:"github_installation_id"`
	GithubRepositoryID   pgtype.Int8 `json:"github_repository_id"`
	Private              bool        `json:"private"`
}

func (q *Queries) UpsertGitSource(ctx context.Context, arg UpsertGitSourceParams) (AppGitSource, error) {
	row := q.db.QueryRow(ctx, upsertGitSource,
		arg.AppID,
		arg.Repository,
		arg.Branch,
		arg.BuildContext,
		arg.DockerfilePath,
		arg.AccessMode,
		arg.GithubInstallationID,
		arg.GithubRepositoryID,
		arg.Private,
	)
	var i AppGitSource
	err := row.Scan(
		&i.AppID,
		&i.Repository,
		&i.Branch,
		&i.BuildContext,
		&i.DockerfilePath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccessMode,
		&i.GithubInstallationID,
		&i.GithubRepositoryID,
		&i.Private,
	)
	return i, err
}
