// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: github_installation.sql

package sqlc

import (
	"context"
)

const getGitHubInstallation = `-- name: GetGitHubInstallation :one
SELECT installation_id, account_login, account_type, repository_selection, created_at, updated_at FROM github_installations WHERE installation_id = $1
`

func (q *Queries) GetGitHubInstallation(ctx context.Context, installationID int64) (GithubInstallation, error) {
	row := q.db.QueryRow(ctx, getGitHubInstallation, installationID)
	var i GithubInstallation
	err := row.Scan(
		&i.InstallationID,
		&i.AccountLogin,
		&i.AccountType,
		&i.RepositorySelection,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGitHubInstallations = `-- name: ListGitHubInstallations :many
SELECT installation_id, account_login, account_type, repository_selection, created_at, updated_at FROM github_installations ORDER BY account_login, installation_id
`

func (q *Queries) ListGitHubInstallations(ctx context.Context) ([]GithubInstallation, error) {
	rows, err := q.db.Query(ctx, listGitHubInstallations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GithubInstallation
	for rows.Next() {
		var i GithubInstallation
		if err := rows.Scan(
			&i.InstallationID,
			&i.AccountLogin,
			&i.AccountType,
			&i.RepositorySelection,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGitHubInstallation = `-- name: UpsertGitHubInstallation :one
INSERT INTO github_installations (installation_id, account_login, account_type, repository_selection)
VALUES ($1, $2, $3, $4)
ON CONFLICT (installation_id) DO UPDATE SET
    account_login = EXCLUDED.account_login,
    account_type = EXCLUDED.account_type,
    repository_selection = EXCLUDED.repository_selection,
    updated_at = now()
RETURNING installation_id, account_login, account_type, repository_selection, created_at, updated_at
`

type UpsertGitHubInstallationParams struct {
	InstallationID      int64  `json:"installation_id"`
	AccountLogin        string `json:"account_login"`
	AccountType         string `json:"account_type"`
	RepositorySelection string `json:"repository_selection"`
}

func (q *Queries) UpsertGitHubInstallation(ctx context.Context, arg UpsertGitHubInstallationParams) (GithubInstallation, error) {
	row := q.db.QueryRow(ctx, upsertGitHubInstallation,
		arg.InstallationID,
		arg.AccountLogin,
		arg.AccountType,
		arg.RepositorySelection,
	)
	var i GithubInstallation
	err := row.Scan(
		&i.InstallationID,
		&i.AccountLogin,
		&i.AccountType,
		&i.RepositorySelection,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
