// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: github_webhook.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimGitHubWebhookDelivery = `-- name: ClaimGitHubWebhookDelivery :one
INSERT INTO github_webhook_deliveries (delivery_id, event, repository_id, commit_sha)
VALUES ($1, $2, $3, $4)
ON CONFLICT (delivery_id) DO NOTHING
RETURNING delivery_id
`

type ClaimGitHubWebhookDeliveryParams struct {
	DeliveryID   string      `json:"delivery_id"`
	Event        string      `json:"event"`
	RepositoryID pgtype.Int8 `json:"repository_id"`
	CommitSha    pgtype.Text `json:"commit_sha"`
}

func (q *Queries) ClaimGitHubWebhookDelivery(ctx context.Context, arg ClaimGitHubWebhookDeliveryParams) (string, error) {
	row := q.db.QueryRow(ctx, claimGitHubWebhookDelivery,
		arg.DeliveryID,
		arg.Event,
		arg.RepositoryID,
		arg.CommitSha,
	)
	var delivery_id string
	err := row.Scan(&delivery_id)
	return delivery_id, err
}

const completeGitHubWebhookDelivery = `-- name: CompleteGitHubWebhookDelivery :exec
UPDATE github_webhook_deliveries
SET status = $1,
    error_message = $2,
    processed_at = now()
WHERE delivery_id = $3
`

type CompleteGitHubWebhookDeliveryParams struct {
	Status       string      `json:"status"`
	ErrorMessage pgtype.Text `json:"error_message"`
	DeliveryID   string      `json:"delivery_id"`
}

func (q *Queries) CompleteGitHubWebhookDelivery(ctx context.Context, arg CompleteGitHubWebhookDeliveryParams) error {
	_, err := q.db.Exec(ctx, completeGitHubWebhookDelivery, arg.Status, arg.ErrorMessage, arg.DeliveryID)
	return err
}
