// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiToken struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Name        string             `json:"name"`
	TokenHash   string             `json:"token_hash"`
	TokenPrefix string             `json:"token_prefix"`
	Scopes      []string           `json:"scopes"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type App struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	PublicUrl   pgtype.Text        `json:"public_url"`
	OwnerUserID pgtype.UUID        `json:"owner_user_id"`
}

type AppGitSource struct {
	AppID                pgtype.UUID        `json:"app_id"`
	Repository           string             `json:"repository"`
	Branch               string             `json:"branch"`
	BuildContext         string             `json:"build_context"`
	DockerfilePath       string             `json:"dockerfile_path"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	AccessMode           string             `json:"access_mode"`
	GithubInstallationID pgtype.Int8        `json:"github_installation_id"`
	GithubRepositoryID   pgtype.Int8        `json:"github_repository_id"`
	Private              bool               `json:"private"`
	AutoDeploy           bool               `json:"auto_deploy"`
}

type AuditEvent struct {
	ID         int64              `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Action     string             `json:"action"`
	Method     string             `json:"method"`
	Path       string             `json:"path"`
	StatusCode int32              `json:"status_code"`
	RequestID  string             `json:"request_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type CustomDomain struct {
	ID         pgtype.UUID        `json:"id"`
	AppID      pgtype.UUID        `json:"app_id"`
	Hostname   string             `json:"hostname"`
	Status     string             `json:"status"`
	LastError  pgtype.Text        `json:"last_error"`
	VerifiedAt pgtype.Timestamptz `json:"verified_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Deployment struct {
	ID                   pgtype.UUID        `json:"id"`
	AppID                pgtype.UUID        `json:"app_id"`
	ImageTag             string             `json:"image_tag"`
	Status               string             `json:"status"`
	ContainerID          pgtype.Text        `json:"container_id"`
	Port                 pgtype.Int4        `json:"port"`
	CommitSha            pgtype.Text        `json:"commit_sha"`
	DurationMs           pgtype.Int4        `json:"duration_ms"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	FinishedAt           pgtype.Timestamptz `json:"finished_at"`
	SourceType           string             `json:"source_type"`
	Repository           pgtype.Text        `json:"repository"`
	Branch               pgtype.Text        `json:"branch"`
	CommitAuthor         pgtype.Text        `json:"commit_author"`
	CommitMessage        pgtype.Text        `json:"commit_message"`
	TriggerType          string             `json:"trigger_type"`
	GithubDeliveryID     pgtype.Text        `json:"github_delivery_id"`
	Attempt              int32              `json:"attempt"`
	RetryOf              pgtype.UUID        `json:"retry_of"`
	CancelRequested      bool               `json:"cancel_requested"`
	CandidateContainerID pgtype.Text        `json:"candidate_container_id"`
	CandidatePort        pgtype.Int4        `json:"candidate_port"`
}

type DeploymentLog struct {
	ID           int64              `json:"id"`
	DeploymentID pgtype.UUID        `json:"deployment_id"`
	Stage        string             `json:"stage"`
	Stream       string             `json:"stream"`
	Message      string             `json:"message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type EnvVar struct {
	ID        pgtype.UUID        `json:"id"`
	AppID     pgtype.UUID        `json:"app_id"`
	Key       string             `json:"key"`
	Value     []byte             `json:"value"`
	Nonce     []byte             `json:"nonce"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type GithubInstallation struct {
	InstallationID      int64              `json:"installation_id"`
	AccountLogin        string             `json:"account_login"`
	AccountType         string             `json:"account_type"`
	RepositorySelection string             `json:"repository_selection"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	OwnerUserID         pgtype.UUID        `json:"owner_user_id"`
}

type GithubWebhookDelivery struct {
	DeliveryID   string             `json:"delivery_id"`
	Event        string             `json:"event"`
	RepositoryID pgtype.Int8        `json:"repository_id"`
	CommitSha    pgtype.Text        `json:"commit_sha"`
	Status       string             `json:"status"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ProcessedAt  pgtype.Timestamptz `json:"processed_at"`
}

type RollbackHistory struct {
	ID             pgtype.UUID        `json:"id"`
	AppID          pgtype.UUID        `json:"app_id"`
	FromDeployment pgtype.UUID        `json:"from_deployment"`
	ToDeployment   pgtype.UUID        `json:"to_deployment"`
	TriggeredBy    pgtype.Text        `json:"triggered_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
