// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type App struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Deployment struct {
	ID          pgtype.UUID        `json:"id"`
	AppID       pgtype.UUID        `json:"app_id"`
	ImageTag    string             `json:"image_tag"`
	Status      string             `json:"status"`
	ContainerID pgtype.Text        `json:"container_id"`
	Port        pgtype.Int4        `json:"port"`
	CommitSha   pgtype.Text        `json:"commit_sha"`
	DurationMs  pgtype.Int4        `json:"duration_ms"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	FinishedAt  pgtype.Timestamptz `json:"finished_at"`
}

type EnvVar struct {
	ID        pgtype.UUID        `json:"id"`
	AppID     pgtype.UUID        `json:"app_id"`
	Key       string             `json:"key"`
	Value     []byte             `json:"value"`
	Nonce     []byte             `json:"nonce"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type RollbackHistory struct {
	ID             pgtype.UUID        `json:"id"`
	AppID          pgtype.UUID        `json:"app_id"`
	FromDeployment pgtype.UUID        `json:"from_deployment"`
	ToDeployment   pgtype.UUID        `json:"to_deployment"`
	TriggeredBy    pgtype.Text        `json:"triggered_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
