// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rollback.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const recordRollback = `-- name: RecordRollback :exec
INSERT INTO rollback_history (app_id, from_deployment, to_deployment, triggered_by)
VALUES ($1, $2, $3, $4)
`

type RecordRollbackParams struct {
	AppID          pgtype.UUID `json:"app_id"`
	FromDeployment pgtype.UUID `json:"from_deployment"`
	ToDeployment   pgtype.UUID `json:"to_deployment"`
	TriggeredBy    pgtype.Text `json:"triggered_by"`
}

func (q *Queries) RecordRollback(ctx context.Context, arg RecordRollbackParams) error {
	_, err := q.db.Exec(ctx, recordRollback,
		arg.AppID,
		arg.FromDeployment,
		arg.ToDeployment,
		arg.TriggeredBy,
	)
	return err
}
